png('plot2.png',width=480,height=480)
data<-read.table('household_power_consumption.txt',sep=';',header=T,na.strings='?',stringsAsFactors=F)
data_sub<-subset(data,data$Date=='1/2/2007'|data$Date=='2/2/2007')
time<-paste(as.Date(data_sub$Date,format='%d/%m/%Y'),data_sub$Time)
timex<-as.POSIXct(time)
TT<-unclass(timex)
N<-nrow(data_sub)
plot(TT,data_sub$Global_active_power,xaxt='n',type='l',cex=1,lty=1,xlab='',ylab='Global Active Power (kilowatts)')
axis(1,labels='Thu',at=unclass(timex)[1],las=1)
axis(1,labels='Fri',at=unclass(timex)[N/2],las=1)
axis(1,labels='Sat',at=unclass(timex)[N],las=1)
dev.off()